#ifndef CONFIGURATION_H_INCLUIDED
#define CONFIGURATION_H_INCLUIDED

extern int NUMBER_OF_THREADS;

extern int NUMBER_OF_ITERATIONS;

extern int NUMBER_OF_CENTROIDS;

extern int NUMBER_OF_POINTS;

// debug logs
extern int DEBUG_LOGS;

extern int TIMES;

#endif // CONFIGURATION_H_INCLUIDED